name: Manual Workflow
on:
  workflow_dispatch:
    inputs:
      param1:
        description: "Enter the first parameter"
        required: true
        type: string
      param2:
        description: "Enter the second parameter"
        required: false
        type: string
env:
 MY_URL: ${{vars.URL}},
jobs:
  run-manually:
    runs-on: ubuntu-latest
    environment: TEST-ENVIRONMENT
    env:
      ENV_URL: ${{vars.URL}}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Display inputs
        run: |
          echo "Encoding and storing password in a file for testing."
          echo "${{ secrets.PASSWORD  }}" | base64 > password.txt
          echo "${{ secrets.INPUT_PASSWORD  }}" | base64 > env.txt
          echo "Encoded password saved to password.txt"
          echo "Param1: ${{ github.event.inputs.param1 }}"
          echo "Param2: ${{ github.event.inputs.param2 }}"
          echo "Environment Variable (vars.URL): ${{ vars.URL }}"  # Corrected reference to the vars URL
          echo "Environment Variable (env.ENV_URL): $ENV_URL"  # Accessing shell env variable ENV_URL
          echo "repository Variable (MY_URL): $MY_URL"  # Accessing the MY_URL shell env variable

      - name: Upload password for testing
        uses: actions/upload-artifact@v3
        with:
          name: encoded-password
          path: password.txt
      - name: Upload password for env testing
        uses: actions/upload-artifact@v3
        with:
          name: encoded-password
          path: env.txt
