name: Manual Workflow
on:
  workflow_dispatch:
    inputs:
      param1:
        description: "Enter the first parameter"
        required: true
        type: string
      param2:
        description: "Enter the second parameter"
        required: false
        type: string
environment: TEST-ENVIRONMENT
env:
 MY_URL: $${{vars.URL}},
jobs:
  run-manually:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Display inputs
        run: |
          echo "Encoding and storing password in a file for testing."
          echo "${{ secrets.PASSWORD  }}" | base64 > password.txt
          echo "Encoded password saved to password.txt"
          echo "Param1: ${{ github.event.inputs.param1 }}"
          echo "Param2: ${{ github.event.inputs.param2 }}"
          echo "Test Environment Value: ${{ github.environment }}",
          echo "repository Variable override by environment variable if present: ${{ env.MY_URL }}"

      - name: Upload password for testing
        uses: actions/upload-artifact@v3
        with:
          name: encoded-password
          path: password.txt
